apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  initContainers:
    - name: init-script-downloader
      image: appropriate/curl
      args:
        - '-o'
        - '/data/myfile.txt'
        - 'https://raw.githubusercontent.com/BGLCorp/devops-interview-tests/85f6c340cda8e858f563302c8f812ae84bf672da/myfile.txt'
      volumeMounts:
        - name: temp # mount the volume where downloaded file will be saved
          mountPath: /data
  containers:
    - name: myapp-container
      image: alpine:latest
      command: ['sh', '-c', 'cat /data/myfile.txt']
      volumeMounts:
        - mountPath: /data
          name: temp
  volumes:
    - emptyDir: {}
      name: temp
